<!DOCTYPE html>

<!-- define angular app -->
<html>
<head>
    <!-- CSS (load bootstrap) -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <style>
        .navbar { border-radius:0; }
    </style>

    <!-- JS (load angular, ui-router, and our custom js file) -->
    <script src="http://code.angularjs.org/1.2.13/angular.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.8/angular-ui-router.min.js"></script>
    <script src="app.js"></script>
</head>

<!-- apply our angular app to our site -->
<body ng-app="mayoupiApp">

<!-- NAVIGATION -->
<nav class="navbar navbar-inverse" role="navigation">
    <ul class="nav navbar-nav">
        <li><a ui-sref="home">Home</a></li>
    </ul>
    <ul class="nav navbar-nav">
        <li><a ui-sref="admin">Admin</a></li>
    </ul>
</nav>

<!-- MAIN CONTENT -->
<div class="container">
    <!-- this is where content will be injected -->
    <div ui-view></div>
</div>

</body>
</html>