<!DOCTYPE html>

<!-- define angular app -->
<html>
<head>
    <!-- CSS (load bootstrap) -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <style>
        .navbar { border-radius:0; }
    </style>

    <!-- JS (load angular, ui-router, and our custom js file) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular-cookies.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.8/angular-ui-router.min.js"></script>
    <script src="public/scripts/ngStorage.min.js"></script>
    <script src="public/app.js"></script>
    <script src="public/services.js"></script>
    <script src="public/controllers.js"></script>
</head>

<!-- apply our angular app to our site -->
<body ng-app="app">

<!-- NAVIGATION -->
<div data-ng-controller="HeaderController">
    <nav class="navbar navbar-inverse" role="navigation">
        <ul class="nav navbar-nav">
            <li data-ng-if="!authentication.token"><a ui-sref="home">Home</a></li>
            <li data-ng-if="authentication.token"><a ui-sref="settings">Profile</a></li>
        </ul>
        <ul class="nav navbar-nav">
            <li><a ui-sref="admin" data-ng-if="authentication.isAdmin">Admin</a></li>
        </ul>
        <ul class="nav navbar-nav pull-right" data-ng-hide="authentication.token">
            <li><a ui-sref="signin">Sign in</a></li>
        </ul>
        <ul class="nav navbar-nav pull-right" data-ng-hide="authentication.token">
            <li><a ui-sref="signup">Sign up</a></li>
        </ul>
        <ul class="nav navbar-nav pull-right" data-ng-if="authentication.token">
            <li><a ui-sref="signout">Sign out</a></li>
        </ul>
    </nav>
</div>

<!-- MAIN CONTENT -->
<div class="container">
    <!-- this is where content will be injected -->
    <div ui-view></div>
</div>

</body>
</html>